Restaurant/Controllers/CumparareController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Restaurant.Controllers;
using Restaurant.Models;
using System.Text;
using System.Threading.Tasks;

namespace Restaurant.Controllers
{
    public class CumparareController : Controller
    {
        // GET: Cumparare
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Total()
        {
            return View();
        }
        [HttpPost]
        public ActionResult TotalResult()
        {
            try
            {
                double suma = CreeareComandaController.sumatotal;
                double plata = Convert.ToDouble(Request["txtSuma"].ToString());
                StringBuilder sb = CreeareComandaController.sb;
                if (plata - suma >= 0)
                {
                    sb.Append("Suma :   " + plata + " lei <br/>");
                    sb.Append("Rest:    " + (plata - suma) + " lei <br/>");
                }
                else
                {
                    sb.Append("Fonduri insuficiente!");
                }
                return Content(sb.ToString());
            }
            catch(Exception ex)
            {
                Task.Run(() => Helpers.TraceWriter.WriteLineToTraceAsync(ex.Message));
                return RedirectToAction("Index");
            }
        }
    }
}

Restaurant/Views/Cumparare/Index.cshtml
@using Restaurant.Models
@model Restaurant.Models.CumparareModel

@{
    ViewBag.Title = "Index";
}

<h2>Creare Comanda</h2>
<fieldset>
    <legend>Creare Comanda</legend>
    <div>@CumparareModel.Total</div>
    @using (Ajax.BeginForm("TotalResult", "Cumparare",
                    new AjaxOptions { UpdateTargetId = "divComanda" }))
    {
        <div id="divComanda"></div>
        <ol>
            @{
                <i>Scrieti doar numere reale, pozitive</i>
                <br />
                @Html.Label("Suma")
                <br />
                @Html.TextBox("txtSuma")
                <br />
            }
        </ol>
        <button>Order</button>
    }
</fieldset>