Restaurant/Controllers/CreeareComandaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Restaurant.Models;
using System.Text;
using System.Threading.Tasks;
//using Restaurant.Helpers;

namespace Restaurant.Controllers
{
    public class CreeareComandaController : Controller
    {
        public static double sumatotal =0;
        public static StringBuilder sb;
        // GET: CreeareComanda
        public ActionResult Index()
        {
            return View();

        }
        public ActionResult CalculateTotal()
        {
            return View();
        }
        [HttpPost]
        public ActionResult CalculateTotalResult()
        {
            try
            {
                MeniuDbContext mdctx = new MeniuDbContext();
                StringBuilder sbChitanta = new StringBuilder();
                string idmeniuri = Request["txtMeniu"].ToString();
                string amount = Request["txtAmount"].ToString();
                StringBuilder sbNeformatat = new StringBuilder();
                while (amount[amount.Length - 1] == ' ')
                {
                    amount = amount.Remove(amount.Length - 1);
                }
                while (idmeniuri[idmeniuri.Length - 1] == ' ')
                {
                    idmeniuri = idmeniuri.Remove(idmeniuri.Length - 1);
                }
                var meniuri = mdctx.Meniuri.ToList();
                List<int> idlist = new List<int>();
                int nrid = 0;
                foreach (string id in idmeniuri.Split(' '))
                {
                    idlist.Add(Convert.ToInt32(id));
                    ++nrid;
                }
                List<int> amountlist = new List<int>();
                int nramount = 0;
                foreach (string amnt in amount.Split(' '))
                {
                    amountlist.Add(Convert.ToInt32(amnt));
                    ++nramount;
                }
                if (nramount == nrid)
                {
                    int[] amountv = new int[nramount];
                    int i = 0;
                    foreach (var iamn in amountlist)
                    {
                        amountv[i] = iamn;
                        ++i;
                    }
                    double suma = 0;
                    i = 0;
                    foreach (int id in idlist)
                    {
                        var meniu = mdctx.Meniuri.SingleOrDefault(m => m.Id == id);
                        if (meniu != null)
                        {
                            if (amountv[i] != 0)
                            {
                                sbChitanta.Append(amountv[i] + "x");
                                sbChitanta.Append(meniu.Nume + "         ");
                                sbChitanta.Append(meniu.Pret + " lei <br/>");
                                sbNeformatat.Append(amountv[i] + "x");
                                sbNeformatat.Append(meniu.Nume + "         ");
                                sbNeformatat.Append(meniu.Pret + " lei\n");
                                suma += amountv[i] * meniu.Pret;
                                sb = sbChitanta;
                            }
                        }
                        ++i;
                    }
                    sumatotal = suma;
                    if (suma != 0)
                    {
                        sbChitanta.Append("<b>Total :</b> " + suma + " lei<br/>");
                        sbNeformatat.Append("Total : " + suma + " lei\n");
                        sbNeformatat.Replace('.',',');
                        CumparareModel.Total = sbNeformatat.ToString();
                        return RedirectToAction("Index", "Cumparare");
                    }
                    else
                    {
                        sbChitanta.Append("Nu ati comandat nimic");
                        return Content(sbChitanta.ToString());
                    }
                }
                else
                {
                    sbChitanta.Append("Lista de id-uri si lista de numar de meniuri nu corespund");
                    return Content(sbChitanta.ToString());
                }
            }
            catch(Exception ex)
            {
                Task.Run(() => Helpers.TraceWriter.WriteLineToTraceAsync(ex.Message));
                return RedirectToAction("Index");
            }

        }
    }
}

Restaurant/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Restaurant.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "The Forest Man este un nou restaurant " +
                "aici pentru a va aduce zambete, dar si pentru a va satisface fanteziile culinare.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Pagina de contact";

            return View();
        }
        public ActionResult ChangeLanguage(string lang)
        {
            Session["lang"] = lang;
            return RedirectToAction("Index", "Home", new { language = lang });
        }
    }
}

Restaurant/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Infiintat in 14.01.2022.</p>

Restaurant/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    Strada Nicolae Iorga<br />
    Nr.222<br />
    <abbr title="Phone">Phone:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Restaurant/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>The Forest Man</h1>
    <p class="lead">Cel mai bun restaurant la care veti manca vreodata.</p>
    <p><a> <li>@Html.ActionLink("Creare comanda", "Index", "CreeareComanda")</li></a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>5 stele</h2>
        <p>
            Am incercat omleta campionilor si va pot spune ca m-a facut sa ma simt ca un campion!
        </p>
        <p><a class="btn btn-default" href="https://www.facebook.com/profile.php?id=100008834352548">Ionut Padurean &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>5 stele</h2>
        <p>Mancarea e extraordinara, iar servirea, EXCELENTA! Nu mai spun de preturi, super accesibile</p>
        <p><a class="btn btn-default" href="https://www.facebook.com/Rares60">Samartean Rares Petru &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>5 stele</h2>
        <p>
            5 stele pentru ca nu pot da mai mult. As manca aici in fiecare zi, dar nu
            ma tine portofelul... Glumesc, preturile atat de reduse, incat mananc a 120-a zi consecutiv aici!
        </p>
        <p><a class="btn btn-default" href="https://www.youtube.com/watch?v=mCdA4bJAGGk&ab_channel=sweetblue.">Sabau David Anton &raquo;</a></p>
    </div>
</div>